// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBNsHLceTLjrBSn7VcrWMZs8FILHqlU7Q',
    appId: '1:944667494311:web:169b5f11df87797a8c1882',
    messagingSenderId: '944667494311',
    projectId: 'capstone-disupensa25',
    authDomain: 'capstone-disupensa25.firebaseapp.com',
    storageBucket: 'capstone-disupensa25.firebasestorage.app',
    measurementId: 'G-RYDYJNQJ8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbs3gLhQPZYmGxv5oj6U-G4T0jQcfUdzQ',
    appId: '1:944667494311:android:a7a8815ea6cbf7d58c1882',
    messagingSenderId: '944667494311',
    projectId: 'capstone-disupensa25',
    storageBucket: 'capstone-disupensa25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqBnet2f4s8Z9626ZOYbK5oujx2bUT708',
    appId: '1:944667494311:ios:0d8a4d7c7cc49a6b8c1882',
    messagingSenderId: '944667494311',
    projectId: 'capstone-disupensa25',
    storageBucket: 'capstone-disupensa25.firebasestorage.app',
    iosBundleId: 'com.example.disupensa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqBnet2f4s8Z9626ZOYbK5oujx2bUT708',
    appId: '1:944667494311:ios:0d8a4d7c7cc49a6b8c1882',
    messagingSenderId: '944667494311',
    projectId: 'capstone-disupensa25',
    storageBucket: 'capstone-disupensa25.firebasestorage.app',
    iosBundleId: 'com.example.disupensa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBNsHLceTLjrBSn7VcrWMZs8FILHqlU7Q',
    appId: '1:944667494311:web:bc60852146040bf18c1882',
    messagingSenderId: '944667494311',
    projectId: 'capstone-disupensa25',
    authDomain: 'capstone-disupensa25.firebaseapp.com',
    storageBucket: 'capstone-disupensa25.firebasestorage.app',
    measurementId: 'G-HV2E3ZNYK3',
  );
}
