import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'login.dart';
import 'petstart.dart';
import 'firebase_options.dart'; // make sure this file exists (generated by FlutterFire CLI)

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const DisupensaApp());
}

class DisupensaApp extends StatelessWidget {
  const DisupensaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Disupensa',
      theme: ThemeData(
        primarySwatch: Colors.brown,
      ),
      debugShowCheckedModeBanner: false,
      home: const LandingScreen(),
    );
  }
}

/// Landing page (your black background + start button)
class LandingScreen extends StatelessWidget {
  const LandingScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Stack(
        fit: StackFit.expand,
        children: [
          // background image with opacity
          Opacity(
            opacity: 0.5,
            child: Image.asset('assets/dogbg.jpg', fit: BoxFit.cover),
          ),

          // logo in top-left corner
          SafeArea(
            child: Align(
              alignment: Alignment.topLeft,
              child: Padding(
                padding: const EdgeInsets.all(12.0),
                child: SizedBox(
                  height: 60.0,
                  width: 60.0,
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(50.0),
                    child: Image.asset('assets/logo.jpg', fit: BoxFit.cover),
                  ),
                ),
              ),
            ),
          ),

          // center content
          Center(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Image.asset(
                  'assets/disupensalogo.jpg',
                  height: 100,
                  width: 100,
                ),
                const SizedBox(height: 8),
                const Text(
                  "Disupensa\nEasy monitoring\nand maintaining\ngood eating habits\nof your pet dog",
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 18.0,
                    color: Colors.white,
                  ),
                ),
                const SizedBox(height: 16),

                // Start Feeding button
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 32.0),
                  child: ElevatedButton(
                    onPressed: () async {
                  // Force sign-out so it always shows login/register first
                    await FirebaseAuth.instance.signOut();

                    Navigator.push(
                         context,
                       MaterialPageRoute(builder: (_) => const LoginPage()),
                     );
                    },
                    style: ElevatedButton.styleFrom(
                      backgroundColor: const Color(0xFF987554),
                      padding: const EdgeInsets.symmetric(
                          vertical: 14.0, horizontal: 24.0),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8.0),
                      ),
                    ),
                    child: const Text(
                      "Start Feeding",
                      style: TextStyle(
                        fontSize: 16.0,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// Handles Firebase Authentication logic
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        if (snapshot.hasData) {
          // User is logged in
          return const PetStart();
        } else {
          // Not logged in
          return const LoginPage();
        }
      },
    );
  }
}
